//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenapiClerk.BackendAPI.SDKClerk.BackendAPI.SDKsas.Models.Components
{
    using Newtonsoft.Json;
    using OpenapiClerk.BackendAPI.SDKClerk.BackendAPI.SDKsas.Utils;
    using System;
    
    public enum ActorTokenStatus
    {
        [JsonProperty("pending")]
        Pending,
        [JsonProperty("accepted")]
        Accepted,
        [JsonProperty("revoked")]
        Revoked,
    }

    public static class ActorTokenStatusExtension
    {
        public static string Value(this ActorTokenStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ActorTokenStatus ToEnum(this string value)
        {
            foreach(var field in typeof(ActorTokenStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ActorTokenStatus)
                    {
                        return (ActorTokenStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ActorTokenStatus");
        }
    }

}