//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Operations
{
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;
    
    public class CreateOrganizationMembershipRequestBody
    {

        /// <summary>
        /// The ID of the user that will be added as a member in the organization.
        /// </summary>
        [JsonProperty("user_id")]
        public string UserId { get; set; } = default!;

        /// <summary>
        /// The role that the new member will have in the organization.
        /// </summary>
        [JsonProperty("role")]
        public string Role { get; set; } = default!;
    }
}