//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Operations
{
    using Clerk.BackendAPI.Models.Operations;
    using Clerk.BackendAPI.Utils;

    public class CreateOrganizationMembershipRequest
    {
        /// <summary>
        /// The ID of the organization where the new membership will be created.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organization_id")]
        public string OrganizationId { get; set; } = default!;

        [SpeakeasyMetadata("request:mediaType=application/json")]
        public CreateOrganizationMembershipRequestBody RequestBody { get; set; } = default!;
    }
}