//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Operations
{
    using Clerk.BackendAPI.Models.Operations;
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// OK
    /// </summary>
    public class CreateSessionTokenFromTemplateResponseBody
    {

        [JsonProperty("object")]
        public CreateSessionTokenFromTemplateObject? Object { get; set; }

        [JsonProperty("jwt")]
        public string? Jwt { get; set; }
    }
}