//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Operations
{
    using Clerk.BackendAPI.Utils;

    public class GetEnterpriseConnectionRequest
    {
        /// <summary>
        /// The ID of the enterprise connection.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=enterprise_connection_id")]
        public string EnterpriseConnectionId { get; set; } = default!;
    }
}