//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Operations
{
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;

    public class GroupRoleMappings
    {
        /// <summary>
        /// The SCIM group ID from the identity provider.
        /// </summary>
        [JsonProperty("scim_group_id")]
        public string ScimGroupId { get; set; } = default!;

        /// <summary>
        /// Optional display name for the SCIM group.
        /// </summary>
        [JsonProperty("scim_group_display_name")]
        public string? ScimGroupDisplayName { get; set; }

        /// <summary>
        /// The organization role ID to assign to members of the SCIM group.
        /// </summary>
        [JsonProperty("role_id")]
        public string RoleId { get; set; } = default!;

        /// <summary>
        /// The precedence for this mapping. If omitted, precedence is assigned by array order.
        /// </summary>
        [JsonProperty("precedence")]
        public long? Precedence { get; set; }
    }
}