//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Operations
{
    using Clerk.BackendAPI.Utils;

    public class ListEnterpriseConnectionsRequest
    {
        /// <summary>
        /// Applies a limit to the number of results returned.<br/>
        /// Can be used for paginating the results together with `offset`.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")]
        public long? Limit { get; set; } = 10;

        /// <summary>
        /// Skip the first `offset` results when paginating.<br/>
        /// Needs to be an integer greater or equal to zero.<br/>
        /// To be used in conjunction with `limit`.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=offset")]
        public long? Offset { get; set; } = 0;

        /// <summary>
        /// Filter enterprise connections by organization ID.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=organization_id")]
        public string? OrganizationId { get; set; }

        /// <summary>
        /// Filter by active status. If true, only active connections are returned. If false, only inactive connections are returned. If omitted, all connections are returned.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=active")]
        public bool? Active { get; set; }
    }
}