//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Operations
{
    using Clerk.BackendAPI.Utils;

    public class RemoveBillingSubscriptionItemDiscountRequest
    {
        /// <summary>
        /// The ID of the subscription item to remove the discount from.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=subscription_item_id")]
        public string SubscriptionItemId { get; set; } = default!;

        /// <summary>
        /// The ID of the discount to remove.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=discount_id")]
        public string DiscountId { get; set; } = default!;
    }
}