//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Operations
{
    using Clerk.BackendAPI.Models.Operations;
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class ResponseBody1
    {

        [JsonProperty("object")]
        public ResponseBodyObject Object { get; set; } = default!;

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        [JsonProperty("client_id")]
        public string ClientId { get; set; } = default!;

        [JsonProperty("subject")]
        public string Subject { get; set; } = default!;

        [JsonProperty("scopes")]
        public List<string> Scopes { get; set; } = default!;

        [JsonProperty("revoked")]
        public bool Revoked { get; set; } = default!;

        [JsonProperty("revocation_reason", NullValueHandling = NullValueHandling.Include)]
        public string? RevocationReason { get; set; }

        [JsonProperty("expired")]
        public bool Expired { get; set; } = default!;

        [JsonProperty("expiration", NullValueHandling = NullValueHandling.Include)]
        public double? Expiration { get; set; }

        [JsonProperty("created_at")]
        public double CreatedAt { get; set; } = default!;

        [JsonProperty("updated_at")]
        public double UpdatedAt { get; set; } = default!;
    }
}