//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Operations
{
    using Clerk.BackendAPI.Models.Operations;
    using Clerk.BackendAPI.Utils;

    public class RevokeM2MTokenRequest
    {
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=m2m_token_id")]
        public string M2mTokenId { get; set; } = default!;

        [SpeakeasyMetadata("request:mediaType=application/json")]
        public RevokeM2MTokenRequestBody RequestBody { get; set; } = default!;
    }
}