//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Operations
{
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Filter sessions by the provided status
    /// </summary>
    public enum Status
    {
        [JsonProperty("abandoned")]
        Abandoned,
        [JsonProperty("active")]
        Active,
        [JsonProperty("ended")]
        Ended,
        [JsonProperty("expired")]
        Expired,
        [JsonProperty("removed")]
        Removed,
        [JsonProperty("replaced")]
        Replaced,
        [JsonProperty("revoked")]
        Revoked,
    }

    public static class StatusExtension
    {
        public static string Value(this Status value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Status ToEnum(this string value)
        {
            foreach(var field in typeof(Status).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is Status)
                    {
                        return (Status)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum Status");
        }
    }

}