//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Operations
{
    using Clerk.BackendAPI.Models.Operations;
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public class Two
    {

        /// <summary>
        /// The name to use as a label for this SAML Connection
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// The domain of your organization. Sign in flows using an email with this domain, will use this SAML Connection.
        /// </summary>
        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible")]
        [JsonProperty("domain")]
        public string? Domain { get; set; }

        /// <summary>
        /// The domains of your organization. Sign in flows using an email with one of these domains, will use this SAML Connection.
        /// </summary>
        [JsonProperty("domains")]
        public List<string> Domains { get; set; } = default!;

        /// <summary>
        /// The IdP provider of the connection.
        /// </summary>
        [JsonProperty("provider")]
        public RequestBodyProvider Provider { get; set; } = default!;

        /// <summary>
        /// The Entity ID as provided by the IdP
        /// </summary>
        [JsonProperty("idp_entity_id")]
        public string? IdpEntityId { get; set; } = null;

        /// <summary>
        /// The Single-Sign On URL as provided by the IdP
        /// </summary>
        [JsonProperty("idp_sso_url")]
        public string? IdpSsoUrl { get; set; } = null;

        /// <summary>
        /// The X.509 certificate as provided by the IdP
        /// </summary>
        [JsonProperty("idp_certificate")]
        public string? IdpCertificate { get; set; } = null;

        /// <summary>
        /// The URL which serves the IdP metadata. If present, it takes priority over the corresponding individual properties
        /// </summary>
        [JsonProperty("idp_metadata_url")]
        public string? IdpMetadataUrl { get; set; } = null;

        /// <summary>
        /// The XML content of the IdP metadata file. If present, it takes priority over the corresponding individual properties
        /// </summary>
        [JsonProperty("idp_metadata")]
        public string? IdpMetadata { get; set; } = null;

        /// <summary>
        /// The ID of the organization to which users of this SAML Connection will be added
        /// </summary>
        [JsonProperty("organization_id")]
        public string? OrganizationId { get; set; } = null;

        /// <summary>
        /// Define the attribute name mapping between Identity Provider and Clerk&apos;s user properties
        /// </summary>
        [JsonProperty("attribute_mapping")]
        public RequestBodyAttributeMapping? AttributeMapping { get; set; } = null;

        /// <summary>
        /// Enable or deactivate ForceAuthn
        /// </summary>
        [JsonProperty("force_authn")]
        public bool? ForceAuthn { get; set; }
    }
}