//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Operations
{
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;

    public class UpdateInstanceProtectRequestBody
    {
        /// <summary>
        /// Set true to enforce Protect rules on this instance. Set false to stop enforcing and return the instance to its default posture, where traffic is still evaluated in shadow but nothing is blocked. This does not remove the instance from Protect.
        /// </summary>
        [JsonProperty("rules_enabled")]
        public bool? RulesEnabled { get; set; } = null;

        [JsonProperty("specter_enabled")]
        public bool? SpecterEnabled { get; set; } = null;
    }
}