//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Operations
{
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;

    public class UpdateInstanceOAuthApplicationSettingsRequestBody
    {
        /// <summary>
        /// Whether dynamic OAuth client registration is enabled for the instance (RFC 7591).
        /// </summary>
        [JsonProperty("dynamic_oauth_client_registration")]
        public bool? DynamicOauthClientRegistration { get; set; } = null;

        /// <summary>
        /// Whether OAuth JWT access tokens are enabled for the instance (disabled indicates opaque access tokens).
        /// </summary>
        [JsonProperty("oauth_jwt_access_tokens")]
        public bool? OauthJwtAccessTokens { get; set; } = null;
    }
}