//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Operations
{
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class UpdateSCIMDirectoryRequestBody
    {
        /// <summary>
        /// A human-friendly name for the SCIM directory.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Whether the SCIM directory is enabled.
        /// </summary>
        [JsonProperty("enabled")]
        public bool? Enabled { get; set; }

        /// <summary>
        /// The identity provider for this SCIM directory.
        /// </summary>
        [JsonProperty("provider")]
        public string? Provider { get; set; }

        /// <summary>
        /// Attribute-to-SCIM-path entries to merge into the directory's attribute mapping.<br/>
        /// Set a key to `null` to remove it from the mapping.
        /// </summary>
        [JsonProperty("attribute_mapping")]
        public Dictionary<string, string?>? AttributeMapping { get; set; }

        /// <summary>
        /// Whether group-to-role mapping is enabled for this SCIM directory.
        /// </summary>
        [JsonProperty("group_role_mapping_enabled")]
        public bool? GroupRoleMappingEnabled { get; set; }
    }
}