//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Operations
{
    using Clerk.BackendAPI.Models.Operations;
    using Clerk.BackendAPI.Utils;
    
    public class UpsertTemplateRequest
    {

        /// <summary>
        /// The type of template to update
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=template_type")]
        public UpsertTemplatePathParamTemplateType TemplateType { get; set; } = default!;

        /// <summary>
        /// The slug of the template to update
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=slug")]
        public string Slug { get; set; } = default!;

        [SpeakeasyMetadata("request:mediaType=application/json")]
        public UpsertTemplateRequestBody? RequestBody { get; set; }
    }
}