//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Errors
{
    using Clerk.BackendAPI.Models.Components;
    using Clerk.BackendAPI.Models.Errors;
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;

    public class GetM2MTokensResponseBodyPayload
    {
        [JsonProperty("errors")]
        public List<GetM2MTokensErrors> Errors { get; set; } = default!;

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;
    }

    /// <summary>
    /// 400 Bad Request.
    /// </summary>
    public class GetM2MTokensResponseBody : SDKBaseError
    {
        /// <summary>
        ///  The original data that was passed to this exception.
        /// </summary>
        public GetM2MTokensResponseBodyPayload Payload { get; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use GetM2MTokensResponseBody.Payload.Errors instead.")]
        public List<GetM2MTokensErrors> Errors { get; set; } = default!;

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use GetM2MTokensResponseBody.Payload.HttpMeta instead.")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        public GetM2MTokensResponseBody(
            GetM2MTokensResponseBodyPayload payload,
            HttpRequestMessage request,
            HttpResponseMessage response,
            string body
        ): base("API error occurred", request, response, body)
        {
           Payload = payload;

           #pragma warning disable CS0618
           Errors = payload.Errors;
           HttpMeta = payload.HttpMeta;
           #pragma warning restore CS0618
        }
    }
}