//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenapiClerk.BackendAPI.SDKClerk.BackendAPI.SDKsas.Models.Requests
{
    using OpenapiClerk.BackendAPI.SDKClerk.BackendAPI.SDKsas.Utils;
    
    /// <summary>
    /// The actor payload. It needs to include a sub property which should contain the ID of the actor.<br/>
    /// 
    /// <remarks>
    /// This whole payload will be also included in the JWT session token.
    /// </remarks>
    /// </summary>
    public class Actor
    {
    }
}