//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenapiClerk.BackendAPI.SDKClerk.BackendAPI.SDKsas.Models.Requests
{
    using OpenapiClerk.BackendAPI.SDKClerk.BackendAPI.SDKsas.Utils;
    
    public class DeleteAllowlistIdentifierRequest
    {

        /// <summary>
        /// The ID of the identifier to delete from the allow-list
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=identifier_id")]
        public string IdentifierId { get; set; } = default!;
    }
}