//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenapiClerk.BackendAPI.SDKClerk.BackendAPI.SDKsas.Models.Requests
{
    using OpenapiClerk.BackendAPI.SDKClerk.BackendAPI.SDKsas.Utils;
    
    public class GetOrganizationRequest
    {

        /// <summary>
        /// The ID or slug of the organization
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organization_id")]
        public string OrganizationId { get; set; } = default!;

        /// <summary>
        /// Flag to denote whether or not the organization&apos;s members count should be included in the response.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=include_members_count")]
        public bool? IncludeMembersCount { get; set; }
    }
}