//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenapiClerk.BackendAPI.SDKClerk.BackendAPI.SDKsas.Models.Requests
{
    using OpenapiClerk.BackendAPI.SDKClerk.BackendAPI.SDKsas.Models.Requests;
    using OpenapiClerk.BackendAPI.SDKClerk.BackendAPI.SDKsas.Utils;
    
    public class GetTemplateRequest
    {

        /// <summary>
        /// The type of templates to retrieve (email or SMS)
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=template_type")]
        public PathParamTemplateType TemplateType { get; set; } = default!;

        /// <summary>
        /// The slug (i.e. machine-friendly name) of the template to retrieve
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=slug")]
        public string Slug { get; set; } = default!;
    }
}