//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenapiClerk.BackendAPI.SDKClerk.BackendAPI.SDKsas.Models.Requests
{
    using OpenapiClerk.BackendAPI.SDKClerk.BackendAPI.SDKsas.Utils;
    
    public class RotateOAuthApplicationSecretRequest
    {

        /// <summary>
        /// The ID of the OAuth application for which to rotate the client secret
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=oauth_application_id")]
        public string OauthApplicationId { get; set; } = default!;
    }
}