//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;
    using System;

    public enum AutomationDisposition
    {
        [JsonProperty("already_satisfied")]
        AlreadySatisfied,
        [JsonProperty("safe_to_create")]
        SafeToCreate,
        [JsonProperty("manual_resolution_required")]
        ManualResolutionRequired,
    }

    public static class AutomationDispositionExtension
    {
        public static string Value(this AutomationDisposition value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static AutomationDisposition ToEnum(this string value)
        {
            foreach(var field in typeof(AutomationDisposition).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is AutomationDisposition)
                    {
                        return (AutomationDisposition)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum AutomationDisposition");
        }
    }
}