//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Models.Components;
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;

    public class BlocklistIdentifier
    {
        /// <summary>
        /// String representing the object's type. Objects of the same type share the same value.
        /// </summary>
        [JsonProperty("object")]
        public BlocklistIdentifierObject? Object { get; set; }

        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// An email address, email domain, phone number or web3 wallet.
        /// </summary>
        [JsonProperty("identifier")]
        public string? Identifier { get; set; }

        [JsonProperty("identifier_type")]
        public BlocklistIdentifierIdentifierType? IdentifierType { get; set; }

        [JsonProperty("instance_id")]
        public string? InstanceId { get; set; }

        /// <summary>
        /// Unix timestamp of creation.
        /// </summary>
        [JsonProperty("created_at")]
        public long? CreatedAt { get; set; }

        /// <summary>
        /// Unix timestamp of last update.
        /// </summary>
        [JsonProperty("updated_at")]
        public long? UpdatedAt { get; set; }
    }
}