//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Models.Components;
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;

    public class CommercePlanUnitPriceTier
    {
        /// <summary>
        /// Start block (inclusive) for this tier.
        /// </summary>
        [JsonProperty("starts_at_block")]
        public long StartsAtBlock { get; set; } = default!;

        /// <summary>
        /// End block (inclusive) for this tier; null means unlimited.
        /// </summary>
        [JsonProperty("ends_after_block")]
        public long? EndsAfterBlock { get; set; } = null;

        [JsonProperty("fee_per_block")]
        public CommerceMoneyResponse FeePerBlock { get; set; } = default!;
    }
}