//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Models.Components;
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;

    public class CommercePayerResponse
    {
        /// <summary>
        /// String representing the object's type. Objects of the same type share the same value.
        /// </summary>
        [JsonProperty("object")]
        public CommercePayerResponseObject Object { get; set; } = default!;

        /// <summary>
        /// Unique identifier for the payer.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Unique identifier for the Clerk instance.
        /// </summary>
        [JsonProperty("instance_id")]
        public string InstanceId { get; set; } = default!;

        /// <summary>
        /// User ID for user-type payers.
        /// </summary>
        [JsonProperty("user_id")]
        public string? UserId { get; set; } = null;

        /// <summary>
        /// First name of the payer.
        /// </summary>
        [JsonProperty("first_name")]
        public string? FirstName { get; set; } = null;

        /// <summary>
        /// Last name of the payer.
        /// </summary>
        [JsonProperty("last_name")]
        public string? LastName { get; set; } = null;

        /// <summary>
        /// Email address of the payer.
        /// </summary>
        [JsonProperty("email")]
        public string? Email { get; set; } = null;

        /// <summary>
        /// Organization ID for org-type payers.
        /// </summary>
        [JsonProperty("organization_id")]
        public string? OrganizationId { get; set; } = null;

        /// <summary>
        /// Organization name for org-type payers.
        /// </summary>
        [JsonProperty("organization_name")]
        public string? OrganizationName { get; set; } = null;

        /// <summary>
        /// URL of the payer's image/avatar.
        /// </summary>
        [JsonProperty("image_url")]
        public string? ImageUrl { get; set; }

        [JsonProperty("credits_balance")]
        public CommerceMoneyResponse? CreditsBalance { get; set; }

        /// <summary>
        /// Unix timestamp (in milliseconds) when the payer was created.
        /// </summary>
        [JsonProperty("created_at")]
        public long? CreatedAt { get; set; }

        /// <summary>
        /// Unix timestamp (in milliseconds) when the payer was last updated.
        /// </summary>
        [JsonProperty("updated_at")]
        public long? UpdatedAt { get; set; }
    }
}