//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;

    public class DirectoryCustomAttributes
    {
        /// <summary>
        /// Display name for the custom attribute.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Key used to store the attribute in the user's public/private/unsafe metadata.
        /// </summary>
        [JsonProperty("key")]
        public string? Key { get; set; }

        /// <summary>
        /// Path to extract the attribute value from SSO claims (SAML assertions or OIDC claims).
        /// </summary>
        [JsonProperty("sso_path")]
        public string? SsoPath { get; set; }

        /// <summary>
        /// The legacy name for `directory_path`. Carries the same value.
        /// </summary>
        [JsonProperty("scim_path")]
        public string? ScimPath { get; set; }

        /// <summary>
        /// GJSON path to extract the attribute value from directory sync user resources.
        /// </summary>
        [JsonProperty("directory_path")]
        public string? DirectoryPath { get; set; }

        /// <summary>
        /// When true, the attribute supports multiple values; values from the IdP are written to public_metadata as an array. Defaults to false.
        /// </summary>
        [JsonProperty("multi_valued")]
        public bool? MultiValued { get; set; }
    }
}