//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Models.Components;
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// Success
    /// </summary>
    public class EmailAddress
    {

        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// String representing the object&apos;s type. Objects of the same type share the same value.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("object")]
        public EmailAddressObject Object { get; set; } = default!;

        [JsonProperty("email_address")]
        public string EmailAddressValue { get; set; } = default!;

        [JsonProperty("reserved")]
        public bool Reserved { get; set; } = default!;

        [JsonProperty("verification", NullValueHandling = NullValueHandling.Include)]
        public Verification? Verification { get; set; }

        [JsonProperty("linked_to")]
        public List<IdentificationLink> LinkedTo { get; set; } = default!;

        /// <summary>
        /// Indicates whether this email address domain matches an active enterprise connection.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("matches_sso_connection")]
        public bool? MatchesSsoConnection { get; set; }

        /// <summary>
        /// Unix timestamp of creation<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("created_at")]
        public long CreatedAt { get; set; } = default!;

        /// <summary>
        /// Unix timestamp of creation<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("updated_at")]
        public long UpdatedAt { get; set; } = default!;
    }
}