//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Models.Components;
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;

    public class FeatureResponse
    {
        /// <summary>
        /// String representing the object's type. Objects of the same type share the same value.
        /// </summary>
        [JsonProperty("object")]
        public FeatureResponseObject Object { get; set; } = default!;

        /// <summary>
        /// Unique identifier for the feature.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// The name of the feature.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// The description of the feature.
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Include)]
        public string? Description { get; set; }

        /// <summary>
        /// The URL-friendly slug for the feature.
        /// </summary>
        [JsonProperty("slug")]
        public string Slug { get; set; } = default!;

        /// <summary>
        /// The URL of the feature's avatar image.
        /// </summary>
        [JsonProperty("avatar_url", NullValueHandling = NullValueHandling.Include)]
        public string? AvatarUrl { get; set; }
    }
}