//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Models.Components;
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Success
    /// </summary>
    public class InstanceRestrictions
    {

        /// <summary>
        /// String representing the object&apos;s type. Objects of the same type share the same value.
        /// </summary>
        [JsonProperty("object")]
        public InstanceRestrictionsObject? Object { get; set; }

        [JsonProperty("allowlist")]
        public bool? Allowlist { get; set; }

        [JsonProperty("blocklist")]
        public bool? Blocklist { get; set; }

        [JsonProperty("block_email_subaddresses")]
        public bool? BlockEmailSubaddresses { get; set; }

        [JsonProperty("ignore_dots_for_gmail_addresses")]
        public bool? IgnoreDotsForGmailAddresses { get; set; }
    }
}