//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// String representing the object's type.
    /// </summary>
    public enum MachineSecretKeyObject
    {
        [JsonProperty("machine_secret_key")]
        MachineSecretKey,
    }

    public static class MachineSecretKeyObjectExtension
    {
        public static string Value(this MachineSecretKeyObject value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static MachineSecretKeyObject ToEnum(this string value)
        {
            foreach(var field in typeof(MachineSecretKeyObject).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is MachineSecretKeyObject)
                    {
                        return (MachineSecretKeyObject)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum MachineSecretKeyObject");
        }
    }
}