//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Models.Components;
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Success.
    /// </summary>
    public class MachineSecretKey
    {
        /// <summary>
        /// String representing the object's type.
        /// </summary>
        [JsonProperty("object")]
        public MachineSecretKeyObject Object { get; set; } = default!;

        /// <summary>
        /// The secret key for the machine.
        /// </summary>
        [JsonProperty("secret")]
        public string Secret { get; set; } = default!;
    }
}