//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;
    
    public class ManagementApplicationInstance
    {

        /// <summary>
        /// The ID of the instance.
        /// </summary>
        [JsonProperty("instance_id")]
        public string InstanceId { get; set; } = default!;

        /// <summary>
        /// The environment type of the instance.
        /// </summary>
        [JsonProperty("environment_type")]
        public string EnvironmentType { get; set; } = default!;

        /// <summary>
        /// The secret key of the instance.
        /// </summary>
        [JsonProperty("secret_key")]
        public string SecretKey { get; set; } = default!;

        /// <summary>
        /// The publishable key of the instance.
        /// </summary>
        [JsonProperty("publishable_key")]
        public string PublishableKey { get; set; } = default!;
    }
}