//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Present when the enterprise connection uses OIDC.
    /// </summary>
    public class OauthConfig
    {
        /// <summary>
        /// OAuth config ID.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// Custom OIDC provider display name.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// OAuth provider key (e.g. oidc_custom).
        /// </summary>
        [JsonProperty("provider_key")]
        public string? ProviderKey { get; set; }

        /// <summary>
        /// OAuth client ID.
        /// </summary>
        [JsonProperty("client_id")]
        public string? ClientId { get; set; } = null;

        /// <summary>
        /// OIDC discovery URL.
        /// </summary>
        [JsonProperty("discovery_url")]
        public string? DiscoveryUrl { get; set; } = null;

        /// <summary>
        /// Logo URL for the provider.
        /// </summary>
        [JsonProperty("logo_public_url")]
        public string? LogoPublicUrl { get; set; } = null;

        /// <summary>
        /// Unix timestamp in milliseconds when the config was created.
        /// </summary>
        [JsonProperty("created_at")]
        public long? CreatedAt { get; set; }

        /// <summary>
        /// Unix timestamp in milliseconds when the config was last updated.
        /// </summary>
        [JsonProperty("updated_at")]
        public long? UpdatedAt { get; set; }
    }
}