//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Models.Components;
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// An organization domain.
    /// </summary>
    public class OrganizationDomain
    {
        /// <summary>
        /// String representing the object's type. Objects of the same type share the same value. Always `organization_domain`
        /// </summary>
        [JsonProperty("object")]
        public OrganizationDomainObject Object { get; set; } = default!;

        /// <summary>
        /// Unique identifier for the organization domain.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Unique identifier for the organization.
        /// </summary>
        [JsonProperty("organization_id")]
        public string OrganizationId { get; set; } = default!;

        /// <summary>
        /// Name of the organization domain.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Mode of enrollment for the domain.
        /// </summary>
        [JsonProperty("enrollment_mode")]
        public Models.Components.EnrollmentMode EnrollmentMode { get; set; } = default!;

        /// <summary>
        /// Affiliation email address for the domain, if available.
        /// </summary>
        [JsonProperty("affiliation_email_address", NullValueHandling = NullValueHandling.Include)]
        public string? AffiliationEmailAddress { get; set; }

        /// <summary>
        /// Verification details for the user-facing affiliation between the domain and the organization (e.g. affiliation_email_code).
        /// </summary>
        [JsonProperty("affiliation_verification", NullValueHandling = NullValueHandling.Include)]
        public AffiliationVerification? AffiliationVerification { get; set; }

        /// <summary>
        /// Verification details for the underlying DNS domain ownership proof (TXT challenge or dashboard override). Null until ownership has been attempted.
        /// </summary>
        [JsonProperty("ownership_verification", NullValueHandling = NullValueHandling.Include)]
        public OwnershipVerification? OwnershipVerification { get; set; }

        /// <summary>
        /// Deprecated alias for `affiliation_verification`. Kept for backward compatibility on the current API version; will be removed in the next API version. Prefer `affiliation_verification`.
        /// </summary>
        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible")]
        [JsonProperty("verification", NullValueHandling = NullValueHandling.Include)]
        public OrganizationDomainVerification? Verification { get; set; }

        /// <summary>
        /// Total number of pending invitations associated with this domain.
        /// </summary>
        [JsonProperty("total_pending_invitations")]
        public int TotalPendingInvitations { get; set; } = default!;

        /// <summary>
        /// Total number of pending suggestions associated with this domain.
        /// </summary>
        [JsonProperty("total_pending_suggestions")]
        public int TotalPendingSuggestions { get; set; } = default!;

        /// <summary>
        /// Public organization data associated with this domain.
        /// </summary>
        [JsonProperty("public_organization_data")]
        public PublicOrganizationData? PublicOrganizationData { get; set; } = null;

        /// <summary>
        /// Unix timestamp when the domain was created.
        /// </summary>
        [JsonProperty("created_at")]
        public long CreatedAt { get; set; } = default!;

        /// <summary>
        /// Unix timestamp of the last update to the domain.
        /// </summary>
        [JsonProperty("updated_at")]
        public long UpdatedAt { get; set; } = default!;
    }
}