//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;

    public class PriceTransitionRequest
    {
        /// <summary>
        /// The current price ID of the subscription item.
        /// </summary>
        [JsonProperty("from_price_id")]
        public string FromPriceId { get; set; } = default!;

        /// <summary>
        /// The target price ID to transition to.
        /// </summary>
        [JsonProperty("to_price_id")]
        public string ToPriceId { get; set; } = default!;
    }
}