//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Models.Components;
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// Metadata describing a user's linkage to a directory. Included in user responses when directory data is requested, and in directory-triggered user webhooks. Its absence does not necessarily mean the user is not managed by a directory.
    /// </summary>
    public class SCIMUserMetadata
    {
        /// <summary>
        /// The user's resource ID in this directory.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        [JsonProperty("directory_name")]
        public string DirectoryName { get; set; } = default!;

        [JsonProperty("provider")]
        public string Provider { get; set; } = default!;

        [JsonProperty("enterprise_connection_id", NullValueHandling = NullValueHandling.Include)]
        public string? EnterpriseConnectionId { get; set; }

        /// <summary>
        /// Omitted when groups were not loaded; an empty array means no group memberships.
        /// </summary>
        [JsonProperty("groups")]
        public List<Groups>? Groups { get; set; }

        /// <summary>
        /// The ID of the directory the user is provisioned from.
        /// </summary>
        [JsonProperty("directory_id")]
        public string DirectoryId { get; set; } = default!;

        /// <summary>
        /// Whether the directory is currently enabled.
        /// </summary>
        [JsonProperty("directory_enabled")]
        public bool DirectoryEnabled { get; set; } = default!;

        /// <summary>
        /// The user's external ID as reported by the directory, if any.
        /// </summary>
        [JsonProperty("external_id", NullValueHandling = NullValueHandling.Include)]
        public string? ExternalId { get; set; }
    }
}