//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Models.Components;
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;
    
    public class VerificationSAMLVerificationSAML
    {

        [JsonProperty("object")]
        public VerificationSamlVerificationEnterpriseAccountObject? Object { get; set; }

        [JsonProperty("status")]
        public VerificationSamlVerificationEnterpriseAccountStatus Status { get; set; } = default!;

        [JsonProperty("strategy")]
        public VerificationSamlVerificationEnterpriseAccountStrategy Strategy { get; set; } = default!;

        [JsonProperty("external_verification_redirect_url")]
        public string? ExternalVerificationRedirectUrl { get; set; } = null;

        [JsonProperty("error", NullValueHandling = NullValueHandling.Include)]
        public VerificationSamlVerificationEnterpriseAccountError? Error { get; set; } = null;

        [JsonProperty("expire_at")]
        public long? ExpireAt { get; set; } = null;

        [JsonProperty("attempts", NullValueHandling = NullValueHandling.Include)]
        public long? Attempts { get; set; }

        [JsonProperty("verified_at_client")]
        public string? VerifiedAtClient { get; set; } = null;
    }
}