//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Clerk.BackendAPI.Models.Components
{
    using Clerk.BackendAPI.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class VerificationOauthVerificationStatus : IEquatable<VerificationOauthVerificationStatus>
    {
        public static readonly VerificationOauthVerificationStatus Unverified = new VerificationOauthVerificationStatus("unverified");
        public static readonly VerificationOauthVerificationStatus Verified = new VerificationOauthVerificationStatus("verified");
        public static readonly VerificationOauthVerificationStatus Failed = new VerificationOauthVerificationStatus("failed");
        public static readonly VerificationOauthVerificationStatus Expired = new VerificationOauthVerificationStatus("expired");
        public static readonly VerificationOauthVerificationStatus Transferable = new VerificationOauthVerificationStatus("transferable");

        private static readonly Dictionary <string, VerificationOauthVerificationStatus> _knownValues =
            new Dictionary <string, VerificationOauthVerificationStatus> ()
            {
                ["unverified"] = Unverified,
                ["verified"] = Verified,
                ["failed"] = Failed,
                ["expired"] = Expired,
                ["transferable"] = Transferable
            };

        private static readonly ConcurrentDictionary<string, VerificationOauthVerificationStatus> _values =
            new ConcurrentDictionary<string, VerificationOauthVerificationStatus>(_knownValues);

        private VerificationOauthVerificationStatus(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static VerificationOauthVerificationStatus Of(string value)
        {
            return _values.GetOrAdd(value, _ => new VerificationOauthVerificationStatus(value));
        }

        public static implicit operator VerificationOauthVerificationStatus(string value) => Of(value);
        public static implicit operator string(VerificationOauthVerificationStatus verificationoauthverificationstatus) => verificationoauthverificationstatus.Value;

        public static VerificationOauthVerificationStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as VerificationOauthVerificationStatus);

        public bool Equals(VerificationOauthVerificationStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}