workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    clerk-backend-api-OAS:
        inputs:
            - location: https://raw.githubusercontent.com/clerk/openapi-specs/refs/heads/main/bapi/2025-04-10.yml
        overlays:
            - location: ./examples.yaml
            - location: https://raw.githubusercontent.com/clerk/openapi-specs/refs/heads/main/.speakeasy/bapi/fixes.yml
        registry:
            location: registry.speakeasyapi.dev/clerk/clerk/clerk-openapi
targets:
    clerk-backend-api:
        target: csharp
        source: clerk-backend-api-OAS
        publish:
            nuget:
                apiKey: $nuget_api_key
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/clerk/clerk/clerk-backend-api-oas-csharp-code-samples
            blocking: false
